//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.27 at 01:36:26 PM GMT 
//


package uk.ac.ebi.phis.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.ac.ebi.phis.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.ac.ebi.phis.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Doc }
     * 
     */
    public Doc createDoc() {
        return new Doc();
    }

    /**
     * Create an instance of {@link Image }
     * 
     */
    public Image createImage() {
        return new Image();
    }

    /**
     * Create an instance of {@link Channel }
     * 
     */
    public Channel createChannel() {
        return new Channel();
    }

    /**
     * Create an instance of {@link Roi }
     * 
     */
    public Roi createRoi() {
        return new Roi();
    }

    /**
     * Create an instance of {@link Age }
     * 
     */
    public Age createAge() {
        return new Age();
    }

    /**
     * Create an instance of {@link ZygArray }
     * 
     */
    public ZygArray createZygArray() {
        return new ZygArray();
    }

    /**
     * Create an instance of {@link GenomicLocation }
     * 
     */
    public GenomicLocation createGenomicLocation() {
        return new GenomicLocation();
    }

    /**
     * Create an instance of {@link FloatArray }
     * 
     */
    public FloatArray createFloatArray() {
        return new FloatArray();
    }

    /**
     * Create an instance of {@link GenotypeComponent }
     * 
     */
    public GenotypeComponent createGenotypeComponent() {
        return new GenotypeComponent();
    }

    /**
     * Create an instance of {@link StringArray }
     * 
     */
    public StringArray createStringArray() {
        return new StringArray();
    }

    /**
     * Create an instance of {@link ImageTypeArray }
     * 
     */
    public ImageTypeArray createImageTypeArray() {
        return new ImageTypeArray();
    }

    /**
     * Create an instance of {@link Coordinates }
     * 
     */
    public Coordinates createCoordinates() {
        return new Coordinates();
    }

    /**
     * Create an instance of {@link PositiveIntArray }
     * 
     */
    public PositiveIntArray createPositiveIntArray() {
        return new PositiveIntArray();
    }

    /**
     * Create an instance of {@link PercentArray }
     * 
     */
    public PercentArray createPercentArray() {
        return new PercentArray();
    }

    /**
     * Create an instance of {@link Organism }
     * 
     */
    public Organism createOrganism() {
        return new Organism();
    }

    /**
     * Create an instance of {@link LinkArray }
     * 
     */
    public LinkArray createLinkArray() {
        return new LinkArray();
    }

    /**
     * Create an instance of {@link OntologyTermArray }
     * 
     */
    public OntologyTermArray createOntologyTermArray() {
        return new OntologyTermArray();
    }

    /**
     * Create an instance of {@link Genotype }
     * 
     */
    public Genotype createGenotype() {
        return new Genotype();
    }

    /**
     * Create an instance of {@link IntArray }
     * 
     */
    public IntArray createIntArray() {
        return new IntArray();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link OntologyTerm }
     * 
     */
    public OntologyTerm createOntologyTerm() {
        return new OntologyTerm();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link Dimensions }
     * 
     */
    public Dimensions createDimensions() {
        return new Dimensions();
    }

    /**
     * Create an instance of {@link GenomicLocationArray }
     * 
     */
    public GenomicLocationArray createGenomicLocationArray() {
        return new GenomicLocationArray();
    }

    /**
     * Create an instance of {@link AnnotationArray }
     * 
     */
    public AnnotationArray createAnnotationArray() {
        return new AnnotationArray();
    }

    /**
     * Create an instance of {@link ImageDescription }
     * 
     */
    public ImageDescription createImageDescription() {
        return new ImageDescription();
    }

}
