//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.03 at 04:35:04 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/phisSchema")
package uk.ac.ebi.phis.jaxb;
