//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.20 at 11:42:19 AM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/phisSchema")
package uk.ac.ebi.phis.jaxb;
