package uk.ac.ebi.neo4jUtils;


public enum AnnotationProperties {
	ID, NAME, CREATION_DATE, LAST_MODIFIED_DATE, X_COORDINATES, Y_COORDINATES, Z_COORDINATES, OBSERVATION,
	ABN_IN_ANATOMY_FREETEXT, DEPICTED_ANATOMY_FREETEXT, EXPRESSION_INANATOMY_FREETEXT, PHENOTYPE_FREETEXT 
}
