//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.02 at 05:35:29 PM BST 
//


package j;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Anatomy complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Anatomy">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="anatomy_ontology_id" type="{http://www.example.org/phisSchema}StringArray" minOccurs="0"/>
 *         &lt;element name="anatomy_ontology_term" type="{http://www.example.org/phisSchema}StringArray" minOccurs="0"/>
 *         &lt;element name="anatomy_freetext" type="{http://www.example.org/phisSchema}StringArray" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Anatomy", propOrder = {

})
public class Anatomy {

    @XmlElement(name = "anatomy_ontology_id")
    protected StringArray anatomyOntologyId;
    @XmlElement(name = "anatomy_ontology_term")
    protected StringArray anatomyOntologyTerm;
    @XmlElement(name = "anatomy_freetext")
    protected StringArray anatomyFreetext;

    /**
     * Gets the value of the anatomyOntologyId property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getAnatomyOntologyId() {
        return anatomyOntologyId;
    }

    /**
     * Sets the value of the anatomyOntologyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setAnatomyOntologyId(StringArray value) {
        this.anatomyOntologyId = value;
    }

    /**
     * Gets the value of the anatomyOntologyTerm property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getAnatomyOntologyTerm() {
        return anatomyOntologyTerm;
    }

    /**
     * Sets the value of the anatomyOntologyTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setAnatomyOntologyTerm(StringArray value) {
        this.anatomyOntologyTerm = value;
    }

    /**
     * Gets the value of the anatomyFreetext property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getAnatomyFreetext() {
        return anatomyFreetext;
    }

    /**
     * Sets the value of the anatomyFreetext property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setAnatomyFreetext(StringArray value) {
        this.anatomyFreetext = value;
    }

}
