//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.12 at 05:22:31 PM BST 
//


package j;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Channel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Channel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="associated_image" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="associated_roi" type="{http://www.example.org/phisSchema}StringArray" minOccurs="0"/>
 *         &lt;element name="expressed_genotype_trait" type="{http://www.example.org/phisSchema}GeneticTraitArray"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Channel", propOrder = {

})
public class Channel {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(name = "associated_image", required = true)
    protected String associatedImage;
    @XmlElement(name = "associated_roi")
    protected StringArray associatedRoi;
    @XmlElement(name = "expressed_genotype_trait", required = true)
    protected GeneticTraitArray expressedGenotypeTrait;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the associatedImage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociatedImage() {
        return associatedImage;
    }

    /**
     * Sets the value of the associatedImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociatedImage(String value) {
        this.associatedImage = value;
    }

    /**
     * Gets the value of the associatedRoi property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getAssociatedRoi() {
        return associatedRoi;
    }

    /**
     * Sets the value of the associatedRoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setAssociatedRoi(StringArray value) {
        this.associatedRoi = value;
    }

    /**
     * Gets the value of the expressedGenotypeTrait property.
     * 
     * @return
     *     possible object is
     *     {@link GeneticTraitArray }
     *     
     */
    public GeneticTraitArray getExpressedGenotypeTrait() {
        return expressedGenotypeTrait;
    }

    /**
     * Sets the value of the expressedGenotypeTrait property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneticTraitArray }
     *     
     */
    public void setExpressedGenotypeTrait(GeneticTraitArray value) {
        this.expressedGenotypeTrait = value;
    }

}
