//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.09 at 11:41:20 AM BST 
//


package j;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Coordinares complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Coordinares">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="z_coordinates" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="y_coordinates" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="x_coordinates" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Coordinares", propOrder = {

})
public class Coordinares {

    @XmlElement(name = "z_coordinates")
    protected Float zCoordinates;
    @XmlElement(name = "y_coordinates")
    protected float yCoordinates;
    @XmlElement(name = "x_coordinates")
    protected float xCoordinates;

    /**
     * Gets the value of the zCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getZCoordinates() {
        return zCoordinates;
    }

    /**
     * Sets the value of the zCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setZCoordinates(Float value) {
        this.zCoordinates = value;
    }

    /**
     * Gets the value of the yCoordinates property.
     * 
     */
    public float getYCoordinates() {
        return yCoordinates;
    }

    /**
     * Sets the value of the yCoordinates property.
     * 
     */
    public void setYCoordinates(float value) {
        this.yCoordinates = value;
    }

    /**
     * Gets the value of the xCoordinates property.
     * 
     */
    public float getXCoordinates() {
        return xCoordinates;
    }

    /**
     * Sets the value of the xCoordinates property.
     * 
     */
    public void setXCoordinates(float value) {
        this.xCoordinates = value;
    }

}
