//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 02:53:57 PM BST 
//


package j;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Image complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Image">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="organism" type="{http://www.example.org/phisSchema}Organism"/>
 *         &lt;element name="image_description" type="{http://www.example.org/phisSchema}ImageDescription"/>
 *         &lt;element name="phenotyping_center" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gene_id" type="{http://www.example.org/phisSchema}StringArray" minOccurs="0"/>
 *         &lt;element name="gene_name" type="{http://www.example.org/phisSchema}StringArray" minOccurs="0"/>
 *         &lt;element name="genetic_feature_id" type="{http://www.example.org/phisSchema}StringArray" minOccurs="0"/>
 *         &lt;element name="genetic_feature_name" type="{http://www.example.org/phisSchema}StringArray" minOccurs="0"/>
 *         &lt;element name="genetic_feature_ensembl_id" type="{http://www.example.org/phisSchema}StringArray" minOccurs="0"/>
 *         &lt;element name="genomic_location" type="{http://www.example.org/phisSchema}GenomicLocationArray" minOccurs="0"/>
 *         &lt;element name="zygosity" type="{http://www.example.org/phisSchema}ZygArray" minOccurs="0"/>
 *         &lt;element name="procedure" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="conditions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="observations" type="{http://www.example.org/phisSchema}StringArray" minOccurs="0"/>
 *         &lt;element name="associated_roi" type="{http://www.example.org/phisSchema}StringArray" minOccurs="0"/>
 *         &lt;element name="associated_channel" type="{http://www.example.org/phisSchema}StringArray" minOccurs="0"/>
 *         &lt;element name="depicted_anatomical_structure" type="{http://www.example.org/phisSchema}Anatomy" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Image", propOrder = {

})
public class Image {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected Organism organism;
    @XmlElement(name = "image_description", required = true)
    protected ImageDescription imageDescription;
    @XmlElement(name = "phenotyping_center", required = true)
    protected String phenotypingCenter;
    @XmlElement(name = "gene_id")
    protected StringArray geneId;
    @XmlElement(name = "gene_name")
    protected StringArray geneName;
    @XmlElement(name = "genetic_feature_id")
    protected StringArray geneticFeatureId;
    @XmlElement(name = "genetic_feature_name")
    protected StringArray geneticFeatureName;
    @XmlElement(name = "genetic_feature_ensembl_id")
    protected StringArray geneticFeatureEnsemblId;
    @XmlElement(name = "genomic_location")
    protected GenomicLocationArray genomicLocation;
    protected ZygArray zygosity;
    protected String procedure;
    protected String conditions;
    protected StringArray observations;
    @XmlElement(name = "associated_roi")
    protected StringArray associatedRoi;
    @XmlElement(name = "associated_channel")
    protected StringArray associatedChannel;
    @XmlElement(name = "depicted_anatomical_structure")
    protected Anatomy depictedAnatomicalStructure;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the organism property.
     * 
     * @return
     *     possible object is
     *     {@link Organism }
     *     
     */
    public Organism getOrganism() {
        return organism;
    }

    /**
     * Sets the value of the organism property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organism }
     *     
     */
    public void setOrganism(Organism value) {
        this.organism = value;
    }

    /**
     * Gets the value of the imageDescription property.
     * 
     * @return
     *     possible object is
     *     {@link ImageDescription }
     *     
     */
    public ImageDescription getImageDescription() {
        return imageDescription;
    }

    /**
     * Sets the value of the imageDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageDescription }
     *     
     */
    public void setImageDescription(ImageDescription value) {
        this.imageDescription = value;
    }

    /**
     * Gets the value of the phenotypingCenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhenotypingCenter() {
        return phenotypingCenter;
    }

    /**
     * Sets the value of the phenotypingCenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhenotypingCenter(String value) {
        this.phenotypingCenter = value;
    }

    /**
     * Gets the value of the geneId property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getGeneId() {
        return geneId;
    }

    /**
     * Sets the value of the geneId property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setGeneId(StringArray value) {
        this.geneId = value;
    }

    /**
     * Gets the value of the geneName property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getGeneName() {
        return geneName;
    }

    /**
     * Sets the value of the geneName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setGeneName(StringArray value) {
        this.geneName = value;
    }

    /**
     * Gets the value of the geneticFeatureId property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getGeneticFeatureId() {
        return geneticFeatureId;
    }

    /**
     * Sets the value of the geneticFeatureId property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setGeneticFeatureId(StringArray value) {
        this.geneticFeatureId = value;
    }

    /**
     * Gets the value of the geneticFeatureName property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getGeneticFeatureName() {
        return geneticFeatureName;
    }

    /**
     * Sets the value of the geneticFeatureName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setGeneticFeatureName(StringArray value) {
        this.geneticFeatureName = value;
    }

    /**
     * Gets the value of the geneticFeatureEnsemblId property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getGeneticFeatureEnsemblId() {
        return geneticFeatureEnsemblId;
    }

    /**
     * Sets the value of the geneticFeatureEnsemblId property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setGeneticFeatureEnsemblId(StringArray value) {
        this.geneticFeatureEnsemblId = value;
    }

    /**
     * Gets the value of the genomicLocation property.
     * 
     * @return
     *     possible object is
     *     {@link GenomicLocationArray }
     *     
     */
    public GenomicLocationArray getGenomicLocation() {
        return genomicLocation;
    }

    /**
     * Sets the value of the genomicLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenomicLocationArray }
     *     
     */
    public void setGenomicLocation(GenomicLocationArray value) {
        this.genomicLocation = value;
    }

    /**
     * Gets the value of the zygosity property.
     * 
     * @return
     *     possible object is
     *     {@link ZygArray }
     *     
     */
    public ZygArray getZygosity() {
        return zygosity;
    }

    /**
     * Sets the value of the zygosity property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZygArray }
     *     
     */
    public void setZygosity(ZygArray value) {
        this.zygosity = value;
    }

    /**
     * Gets the value of the procedure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcedure() {
        return procedure;
    }

    /**
     * Sets the value of the procedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcedure(String value) {
        this.procedure = value;
    }

    /**
     * Gets the value of the conditions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConditions() {
        return conditions;
    }

    /**
     * Sets the value of the conditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConditions(String value) {
        this.conditions = value;
    }

    /**
     * Gets the value of the observations property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getObservations() {
        return observations;
    }

    /**
     * Sets the value of the observations property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setObservations(StringArray value) {
        this.observations = value;
    }

    /**
     * Gets the value of the associatedRoi property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getAssociatedRoi() {
        return associatedRoi;
    }

    /**
     * Sets the value of the associatedRoi property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setAssociatedRoi(StringArray value) {
        this.associatedRoi = value;
    }

    /**
     * Gets the value of the associatedChannel property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getAssociatedChannel() {
        return associatedChannel;
    }

    /**
     * Sets the value of the associatedChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setAssociatedChannel(StringArray value) {
        this.associatedChannel = value;
    }

    /**
     * Gets the value of the depictedAnatomicalStructure property.
     * 
     * @return
     *     possible object is
     *     {@link Anatomy }
     *     
     */
    public Anatomy getDepictedAnatomicalStructure() {
        return depictedAnatomicalStructure;
    }

    /**
     * Sets the value of the depictedAnatomicalStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anatomy }
     *     
     */
    public void setDepictedAnatomicalStructure(Anatomy value) {
        this.depictedAnatomicalStructure = value;
    }

}
