//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.09 at 03:07:12 PM BST 
//


package j;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Phenotype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Phenotype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="phenotype_ontology_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="phenotype_freetext" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="phenotype_ontology_term" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Phenotype", propOrder = {

})
public class Phenotype {

    @XmlElement(name = "phenotype_ontology_id")
    protected String phenotypeOntologyId;
    @XmlElement(name = "phenotype_freetext")
    protected String phenotypeFreetext;
    @XmlElement(name = "phenotype_ontology_term")
    protected String phenotypeOntologyTerm;

    /**
     * Gets the value of the phenotypeOntologyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhenotypeOntologyId() {
        return phenotypeOntologyId;
    }

    /**
     * Sets the value of the phenotypeOntologyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhenotypeOntologyId(String value) {
        this.phenotypeOntologyId = value;
    }

    /**
     * Gets the value of the phenotypeFreetext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhenotypeFreetext() {
        return phenotypeFreetext;
    }

    /**
     * Sets the value of the phenotypeFreetext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhenotypeFreetext(String value) {
        this.phenotypeFreetext = value;
    }

    /**
     * Gets the value of the phenotypeOntologyTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhenotypeOntologyTerm() {
        return phenotypeOntologyTerm;
    }

    /**
     * Sets the value of the phenotypeOntologyTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhenotypeOntologyTerm(String value) {
        this.phenotypeOntologyTerm = value;
    }

}
