//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.29 at 02:53:57 PM BST 
//


package j;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Roi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Roi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="associated_immage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="x_coordinates" type="{http://www.example.org/phisSchema}IntArray"/>
 *         &lt;element name="y_coordinates" type="{http://www.example.org/phisSchema}IntArray"/>
 *         &lt;element name="z_coordinates" type="{http://www.example.org/phisSchema}IntArray"/>
 *         &lt;element name="anatomy_expression_annotations" type="{http://www.example.org/phisSchema}Anatomy" minOccurs="0"/>
 *         &lt;element name="phenotype_annotations" type="{http://www.example.org/phisSchema}Phenotype" minOccurs="0"/>
 *         &lt;element name="observations" type="{http://www.example.org/phisSchema}StringArray" minOccurs="0"/>
 *         &lt;element name="associated_channel" type="{http://www.example.org/phisSchema}StringArray" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Roi", propOrder = {

})
public class Roi {

    @XmlElement(name = "associated_immage", required = true)
    protected String associatedImmage;
    @XmlElement(required = true)
    protected String id;
    @XmlElement(name = "x_coordinates", required = true)
    protected IntArray xCoordinates;
    @XmlElement(name = "y_coordinates", required = true)
    protected IntArray yCoordinates;
    @XmlElement(name = "z_coordinates", required = true)
    protected IntArray zCoordinates;
    @XmlElement(name = "anatomy_expression_annotations")
    protected Anatomy anatomyExpressionAnnotations;
    @XmlElement(name = "phenotype_annotations")
    protected Phenotype phenotypeAnnotations;
    protected StringArray observations;
    @XmlElement(name = "associated_channel")
    protected StringArray associatedChannel;

    /**
     * Gets the value of the associatedImmage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssociatedImmage() {
        return associatedImmage;
    }

    /**
     * Sets the value of the associatedImmage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssociatedImmage(String value) {
        this.associatedImmage = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the xCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link IntArray }
     *     
     */
    public IntArray getXCoordinates() {
        return xCoordinates;
    }

    /**
     * Sets the value of the xCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntArray }
     *     
     */
    public void setXCoordinates(IntArray value) {
        this.xCoordinates = value;
    }

    /**
     * Gets the value of the yCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link IntArray }
     *     
     */
    public IntArray getYCoordinates() {
        return yCoordinates;
    }

    /**
     * Sets the value of the yCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntArray }
     *     
     */
    public void setYCoordinates(IntArray value) {
        this.yCoordinates = value;
    }

    /**
     * Gets the value of the zCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link IntArray }
     *     
     */
    public IntArray getZCoordinates() {
        return zCoordinates;
    }

    /**
     * Sets the value of the zCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntArray }
     *     
     */
    public void setZCoordinates(IntArray value) {
        this.zCoordinates = value;
    }

    /**
     * Gets the value of the anatomyExpressionAnnotations property.
     * 
     * @return
     *     possible object is
     *     {@link Anatomy }
     *     
     */
    public Anatomy getAnatomyExpressionAnnotations() {
        return anatomyExpressionAnnotations;
    }

    /**
     * Sets the value of the anatomyExpressionAnnotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anatomy }
     *     
     */
    public void setAnatomyExpressionAnnotations(Anatomy value) {
        this.anatomyExpressionAnnotations = value;
    }

    /**
     * Gets the value of the phenotypeAnnotations property.
     * 
     * @return
     *     possible object is
     *     {@link Phenotype }
     *     
     */
    public Phenotype getPhenotypeAnnotations() {
        return phenotypeAnnotations;
    }

    /**
     * Sets the value of the phenotypeAnnotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Phenotype }
     *     
     */
    public void setPhenotypeAnnotations(Phenotype value) {
        this.phenotypeAnnotations = value;
    }

    /**
     * Gets the value of the observations property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getObservations() {
        return observations;
    }

    /**
     * Sets the value of the observations property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setObservations(StringArray value) {
        this.observations = value;
    }

    /**
     * Gets the value of the associatedChannel property.
     * 
     * @return
     *     possible object is
     *     {@link StringArray }
     *     
     */
    public StringArray getAssociatedChannel() {
        return associatedChannel;
    }

    /**
     * Sets the value of the associatedChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringArray }
     *     
     */
    public void setAssociatedChannel(StringArray value) {
        this.associatedChannel = value;
    }

}
